server:
  port: ${APPLICATION_PORT}
spring:
  application:
    name: Innowise-Intership-User-Service

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${CACHE_HOST}
      port: ${CACHE_PORT}

  cache:
    type: redis
    redis:
      time-to-live: 18000
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
auth:
  service:
    url: ${AUTH_SERVICE_URL}