spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false

  data:
    redis:
      port: 0
auth:
  service:
    url: 0
log:
  home:

management:
  otlp:
    tracing:
      endpoint: http://localhost:4317